title: David Podroužek
email: podruh01@gmail.com
author: me
description: >- # this means to ignore newlines until "baseurl:"
  Myšlenky, nápady a experimenty jednoho Ruby vývojáře v Praze
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.podr.cz"
github_username:  podruh
twitter:
  username: podruh01
  card: summary

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .idea/
